# Generated by Django 4.1.7 on 2023-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('air_stay_time', models.CharField(max_length=25)),
                ('cruise_speed', models.PositiveSmallIntegerField()),
                ('cruise_speed_unit', models.CharField(choices=[('Mach', 'Mach'), ('Knot', 'Knot')], max_length=5)),
                ('useful_load_capacity', models.CharField(max_length=50)),
                ('communication_range', models.CharField(max_length=100)),
                ('wingspan', models.PositiveSmallIntegerField()),
                ('length', models.FloatField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
